import { useState } from "react";
import { motion } from "framer-motion";
import { formatCents } from "../data/loadTripsData";

/**
 * Payment confirmation — the reference shown here is the real
 * TopUpOrder.receiptReference generated by the backend on payment.
 */
export default function ConfirmationStep({
  receipt,
  onBackToHome,
  onViewReceipt,
}) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(receipt.reference).catch(() => {});
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="flex flex-col px-6 pt-5 pb-8 min-h-full">
      <div className="flex gap-1.5">
        {Array.from({ length: 4 }).map((_, i) => (
          <span key={i} className="h-1 flex-1 rounded-full bg-gold-500" />
        ))}
      </div>

      <div className="flex-1 flex flex-col items-center justify-center gap-5 py-6">
        <motion.div
          initial={{ scale: 0.5, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{
            type: "spring",
            stiffness: 220,
            damping: 14,
            delay: 0.1,
          }}
          className="h-16 w-16 rounded-full bg-gradient-to-br from-gold-400 to-gold-500 flex items-center justify-center shadow-[0_10px_24px_-8px_rgba(240,180,41,0.7)]"
        >
          <CheckIcon />
        </motion.div>

        <div className="text-center">
          <h1 className="font-display text-2xl font-bold text-ink-900">
            Payment Successful
          </h1>
          <p className="text-slate-500 text-[14px] mt-2 leading-relaxed px-4">
            Your trips have been loaded onto your Gold Card and are ready to
            use.
          </p>
        </div>

        <div className="w-full rounded-xl bg-white border border-ink-900/5 px-4 py-3.5 flex items-center justify-between">
          <div>
            <p className="text-[10px] font-semibold tracking-wide text-slate-500">
              REFERENCE NUMBER
            </p>
            <p className="text-[14px] font-semibold text-ink-900 mt-0.5">
              {receipt.reference}
            </p>
          </div>
          <button
            type="button"
            onClick={handleCopy}
            className="text-slate-400"
            aria-label="Copy reference number"
          >
            {copied ? (
              <span className="text-[11px] text-gold-600 font-medium">
                Copied
              </span>
            ) : (
              <CopyIcon />
            )}
          </button>
        </div>

        <div className="w-full grid grid-cols-2 gap-3">
          <div className="rounded-xl bg-white border border-ink-900/5 px-3.5 py-3">
            <p className="text-[10px] font-semibold tracking-wide text-slate-500">
              AMOUNT PAID
            </p>
            <p className="font-display font-bold text-ink-900 text-[16px] mt-0.5">
              {formatCents(receipt.totalCents)}
            </p>
          </div>
          <div className="rounded-xl bg-cream-200/70 border border-gold-500/15 px-3.5 py-3">
            <p className="text-[10px] font-semibold tracking-wide text-slate-500">
              {receipt.planTrips > 0 ? "TRIPS LOADED" : "VALIDITY"}
            </p>
            <p className="font-display font-bold text-gold-600 text-[16px] mt-0.5">
              {receipt.planTrips > 0 ? receipt.planTrips : `${receipt.planValidDays} days`}
            </p>
          </div>
        </div>

        {receipt.savingsCents > 0 && (
          <div className="w-full rounded-xl bg-cream-100 border border-gold-500/20 px-4 py-3 text-center">
            <p className="text-[12px] font-medium text-ink-900">
              You saved{" "}
              <span className="font-display font-bold text-gold-600">
                {formatCents(receipt.savingsCents)}
              </span>{" "}
              vs paying cash
            </p>
          </div>
        )}

        <div className="w-full flex items-center gap-2.5 rounded-xl bg-white border border-ink-900/5 px-4 py-3.5">
          <BusIcon />
          <div>
            <p className="text-[10px] font-semibold tracking-wide text-slate-500">
              ACTIVE ROUTE
            </p>
            <p className="text-[13px] font-semibold text-ink-900 mt-0.5">
              {receipt.routeLabel}
            </p>
          </div>
        </div>
      </div>

      <div className="flex flex-col gap-3">
        <motion.button
          whileTap={{ scale: 0.97 }}
          type="button"
          onClick={onBackToHome}
          className="btn-gold w-full py-4 text-[15px]"
        >
          Back to Home
        </motion.button>
        <button
          type="button"
          onClick={onViewReceipt}
          className="w-full rounded-xl border border-ink-900/10 py-4 font-display font-semibold text-ink-900 text-[15px]"
        >
          View Receipt
        </button>
      </div>
    </div>
  );
}

function CheckIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      className="h-7 w-7"
      fill="none"
      stroke="#3d2f05"
      strokeWidth="2.4"
    >
      <path
        d="M5 12.5l4.5 4.5L19 7.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function CopyIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      className="h-4.5 w-4.5"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
    >
      <rect x="9" y="9" width="11" height="11" rx="2" />
      <path d="M5 15V6a2 2 0 0 1 2-2h9" strokeLinecap="round" />
    </svg>
  );
}

function BusIcon() {
  return (
    <svg
      viewBox="0 0 24 24"
      className="h-5 w-5 text-gold-500 shrink-0"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
    >
      <rect x="4" y="5" width="16" height="12" rx="2.5" />
      <path d="M4 12h16M8 17v2M16 17v2" strokeLinecap="round" />
    </svg>
  );
}
